export interface PlayerDetail {
  id: number | null;
  name: string;
  number: string | null;
  short_name: string | null;
  position: string | null;
  throwing_hand: string | null;
  batting_hand: string | null;
  batting_style_id: number | null;
  batting_style_description: string | null;
  batting_skill_ids: number[];
  player_type_ids: number[];
  biorhythm_ids: number[];
  bunt: number;
  steal_start: number;
  steal_end: number;
  speed: number;
  injury_rate: number;
  defense_p: number | null;
  defense_c: number | null;
  throwing_c: number | null;
  defense_1b: number | null;
  defense_2b: number | null;
  defense_3b: number | null;
  defense_ss: number | null;
  defense_of: number | null;
  throwing_of: string | null;
  defense_lf: number | null;
  throwing_lf: string | null;
  defense_cf: number | null;
  throwing_cf: string | null;
  defense_rf: number | null;
  throwing_rf: string | null;
  is_pitcher: boolean;
  is_relief_only: boolean;
  starter_stamina: number | null;
  relief_stamina: number | null;
  pitching_style_id: number | null;
  pitching_style_description: string | null;
  pinch_pitching_style_id: number | null;
  pitching_skill_ids: number[];
  catcher_ids: number[];
  catcher_pitching_style_id: number | null;
  partner_pitcher_ids: number[];
  special_defense_c: number | null;
  special_throwing_c: string | null;
}
